#!/bin/bash

checkNotification(){
    json_Data=`termux-notification-list`
    json_Length=`echo  $json_Data | jq length`
    for ((j=0;j<=json_Length-1;j++));
    do
        package_Name=`echo  $json_Data | jq -r .[$j].packageName`
        if [[ $package_Name == "com.android.incallui" ]]
        then
               return false
        fi
    done
}

while true ;
do
        jsonData=`termux-notification-list`
        jsonLength=`echo  $jsonData | jq length`
        for ((i=0;i<=jsonLength-1;i++));
        do
              packageName=`echo  $jsonData | jq -r .[$i].packageName`
              if [[ $packageName == "com.android.incallui" ]]
              then
                    phoneNumber=`echo $jsonData | jq -r .[$i].title`
                    truecallerData=`truecallerjs -s $phoneNumber`
                    if [ $(echo -e '$truecallerData' | jq empty > /dev/null 2>&1; echo $?) -eq 0 ]; 
                    then
                         name=`echo -e $truecallerData  | jq -r .data[0].name`
                         data=`echo -e " Name      :  $name\nNumber  : $phoneNumber"`
                    else
                         data=`echo -e " Name      :  Unknown Name\nNumber  : $phoneNumber\nError     :  $truecallerData"`
                    fi
                    termux-notification -t TruecallerJS -c "$data" --button1 call --button1-action "termux-telephony-call $phoneNumber"
                    until [[ $packageName != "com.android.incallui" ]]
                    do
                          echo "You are on call..."
                          sleep 10
                    done

              fi

        done
done
