#!/bin/bash

while true ;
do
        packageName=`termux-notification-list | jq -r .[0].packageName`
        if [[ $packageName == "com.android.incallui" ]]
        then
          phoneNumber=`termux-notification-list | jq -r .[0].title`
          name=`truecallerjs -s $phoneNumber | jq -r .data[0].name`
          data=`echo -e " Name      :  $name\nNumber  : $phoneNumber\nCountry   : 'IN'"`
          termux-notification -t TruecallerJS -c "$data" --button1 call --button1-action "termux-telephony-call $phoneNumber" --button2 Busy --button2-action "termux-sms-send -n $phoneNumber \"I will call you later\""
          until [[ $packageName != "com.android.incallui" ]]
          do
              echo "You are on call..."
              sleep 5
          done
        fi
done
